
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef _ObjectDictionary_H
#define _ObjectDictionary_H




#include "data.h"



/*2015-12-26：新增,by dengyang */



/*Master定义,消费者心跳计数时间值  4倍关系,使总线负载率低于10%
Producer生产者(Slave)
消费者(Master)
*/
#define	Producer_Heartbeat_Times						0  			//心跳产生周期:ms,0:关闭Slave心跳报文
#define Producer_Heartbeat_TimesFactor      10      //设置heart产生时间的时间系数:(Producer_Heartbeat_Times * Producer_Heartbeat_TimesFactor)

#define	SYNC_CommunicationCyclePeriod				20			//产生同步报文周期:ms,0:关闭MasterNMT同步通讯报文

#define	NMT_GuardTime									      200			//NMTmaster发送 masterSendNMTnodeguard 请求报文的间隔时间值  0:关闭此功能
#define	NMT_LifeTimeFactor							    10			//从机节点判断主机master出错的时间系数:(NMT_LifeTimeFactor * NMT_GuardTime)




/* Prototypes of function provided by object dictionnary */
UNS32 CanObjectDict_valueRangeTest (UNS8 typeValue, void * value);
const indextable * CanObjectDict_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);



extern CO_Data CanObjectDict_Data;//对象数据字典

extern UNS32 CanObjectDict_obj1016[MAX_NodeId_NUM];//Master定义消费者心跳时间间隔

//映射到SlaveTPDO的master的mapdata.
extern UNS32 CanObjectDict_RPDO1_Map[], 
	           CanObjectDict_RPDO2_Map[],
             CanObjectDict_RPDO3_Map[], 
             CanObjectDict_RPDO4_Map[];

//映射到SlaveTPDO的master的mapdata-科亚驱动器.
extern UNS32 CanObjectDict_RPDO1_Keya_Map[], 
	           CanObjectDict_RPDO2_Keya_Map[];

//映射到SlaveTPDO的master的mapdata-Copley驱动器.
extern UNS32 CanObjectDict_RPDO1_Copley_Map[];

extern UNS32 CanObjectDict_RPDO1_Map_FPMode[];

//步科驱动器tpod
extern UNS32 CanObjectDict_TPDO1_Kinco_Map[], 
	           CanObjectDict_TPDO2_Kinco_Map[],
             CanObjectDict_TPDO3_Kinco_Map[],
             CanObjectDict_TPDO4_Kinco_Map[];

//台达驱动器tpod
extern UNS32 CanObjectDict_TPDO1_Delta_Map[], 
	           CanObjectDict_TPDO2_Delta_Map[],
             CanObjectDict_TPDO3_Delta_Map[],
             CanObjectDict_TPDO4_Delta_Map[];

//风得控驱动器tpod
extern UNS32 CanObjectDict_TPDO1_Windcon_Map[], 
	           CanObjectDict_TPDO2_Windcon_Map[],
             CanObjectDict_TPDO3_Windcon_Map[],
             CanObjectDict_TPDO4_Windcon_Map[];

//惠斯通驱动器tpod
extern UNS32 CanObjectDict_TPDO1_Wheatstone_Map[], 
	           CanObjectDict_TPDO2_Wheatstone_Map[],
             CanObjectDict_TPDO3_Wheatstone_Map[],
             CanObjectDict_TPDO4_Wheatstone_Map[];

//科亚驱动器tpod
extern UNS32 CanObjectDict_TPDO1_Keya_Map[], 
	           CanObjectDict_TPDO2_Keya_Map[],
             CanObjectDict_TPDO3_Keya_Map[],
             CanObjectDict_TPDO4_Keya_Map[];

//Copley驱动器tpod
extern UNS32 CanObjectDict_TPDO1_Copley_Map[], 
	           CanObjectDict_TPDO2_Copley_Map[],
             CanObjectDict_TPDO3_Copley_Map[],
             CanObjectDict_TPDO4_Copley_Map[];

extern UNS16 CanObjectDict_Tx_Map10[MAX_NodeId_NUM];
extern INTEGER32 CanObjectDict_Tx_Map11[MAX_NodeId_NUM];
extern INTEGER16 CanObjectDict_Tx_Map12[MAX_NodeId_NUM];
extern INTEGER32 CanObjectDict_Tx_Map18[MAX_NodeId_NUM];  
extern INTEGER32 CanObjectDict_Tx_Map19[MAX_NodeId_NUM];  
extern INTEGER32 CanObjectDict_Tx_Map20[MAX_NodeId_NUM];  
extern INTEGER32 CanObjectDict_Tx_Map21[MAX_NodeId_NUM];  

typedef struct
{
	UNS8  highestSubIndex;                          // 3
	UNS32 COB_ID_Client_to_Server_Transmit_SDO;	    // 0x600 + id
	UNS32 COB_ID_Server_to_Client_Receive_SDO;	    // 0x580 + id
	UNS8  Node_ID_of_the_SDO_Server;	            // id
}obj_link_sdo;

typedef struct
{
	UNS8 highestSubIndex;//5::参数条目数量
	UNS32 COB_ID;	// 这个PDO发送或接收的CANid:0x180/200 + id
	UNS16 Inhibit_times;//生产禁止约束时间(0.1ms)
	UNS16 Event_timer;//事件定时器触发的时间(ms)
	UNS8  SYNC_startvalue;//同步传输的同步起始值
	UNS32 Transmission_type;	//这个PDO发送或接收的传输形式
}obj_link_pdo;


/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
extern UNS16 CanObjectDict_Map_obj2201;







#endif // CanObjectDict_H
