/* !!!!!!!!!! FILE GENERATED by configure. DO NOT EDIT !!!!!!!!!!*/

/* 
This file is part of CanFestival, a library implementing CanOpen Stack.

Copyright (C): Edouard TISSERANT and Francis DUPIN
See COPYING file for copyrights details.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#ifndef _CONFIG_H_
#define _CONFIG_H_

//如下为可配置项，需要根据项目伺服实际数量及类型进行选择
//步骤1：设置驱动器数量，MAX_NodeId_NUM为驱动器数量
//步骤2：根据驱动器类型，选择ObjectDictionary.c中的对象字典 Line5913及Line6050

/*****************************************************************/
//可配置项区域开始 --- 可配置项区域开始
#define MAX_NodeId_NUM												27//定义支持节点的最大数量(0x00-0x20) (0 --- 32)   //if set 1,why can't work?Must set be equal or greater than 4 --- biyabc

//可配置项区域结束 --- 可配置项区域结束
/*****************************************************************/


/* Needed defines by Canfestival lib */
#define MAX_NodeId_Support   										     32 //本程序支持的最大节点数量为32个（0x20） --- 不可更改

/* New define, if SDO_MAX_LENGTH_TRANSFERT is exceeded allocate data buffer dynamically */
#define SDO_MAX_LENGTH_TRANSFER 							        8
#define SDO_BLOCK_SIZE 												        0
#define SDO_MAX_SIMULTANEOUS_TRANSFERS 				        MAX_NodeId_NUM
//#define SDO_DYNAMIC_BUFFER_ALLOCATION
//#define SDO_DYNAMIC_BUFFER_ALLOCATION_SIZE 		(1024)
//#define SDO_MAX_LENGTH_TRANSFERT 							      16
#define NMT_MAX_NODE_ID 											       (MAX_NodeId_NUM+1)
#define SDO_TIMEOUT_MS 												       3000			//SDO,超时值,unit:ms   默认值:3000
#define MAX_NB_TIMER 												         (MAX_NodeId_NUM+5)

/* CANOPEN_BIG_ENDIAN is not defined */
/* US_TO_TIMEVAL_FACTOR is not defined */
/* TIMEVAL is not defined */
/* TIMEVAL_MAX is not defined */
/* RTCAN_SOCKET is not defined */

#define CANOPEN_LITTLE_ENDIAN 							          1		//Cortex-M为小端存储
#define US_TO_TIMEVAL_FACTOR 								          MAX_NodeId_NUM
#define EMCY_MAX_ERRORS 										          MAX_NodeId_NUM
#define LSS_TIMEOUT_MS 											          1000
#define LSS_FS_TIMEOUT_MS 									          100

#define REPEAT_SDO_MAX_SIMULTANEOUS_TRANSFERTS_TIMES(repeat)\
repeat

//限制最大节点数的数量,必须>=1
#define REPEAT_NMT_MAX_NODE_ID_TIMES(repeat)\
repeat 

#define REPEAT_SDO_MAX_SIMULTANEOUS_TRANSFERS_TIMES(repeat)\
repeat

#define REPEAT_EMCY_MAX_ERRORS_TIMES(repeat)\
repeat 

#endif /* _CONFIG_H_ */
